[AC-5504] Initial Allocation Analyzer
masschallenge/app-allocator-scripts pull request #10
Opened 2018-04-19 21:23 UTC by jonkiparsky

This PR adds a class which reads in a scenario (output from generate.py) and an allocation (output from allocate.py) and 

To test: 
run the allocate.py script on some scenario: `python3 allocate.py example.csv > tmp.out`
in the python shell
import the AllocationAnalyzer and use the `quick_setup` function to load the scenario and allocation:
```
>>> from classes.allocation_analyzer import *
>>> aa = quick_setup()
>>> counts = aa.analyze(aa.completed)
>>> summary = aa.summarize(counts)
>>> print ("\n".join(["%s: %s" %(key, val) for key, val in summary.items()]))
total_reads: 10390
Investor_reads: 1782
female_reads: 2458
Other_reads: 2099
...
```

Some changes to previous functionality:
- summary data removed from allocate.py output in order to allow csv reader to read it
- Event headers are now universal across the class
- pulled out the name munging for startups and judges

Things to do, now, later, or never:
- script this basic interaction
- metrics probably want to be objects
- tighter cohesion with Allocator and Generator (ability to talk to those objects directly rather than using csvs as intermediary)
- better analysis
- we're not dealing with judge niceness yet
- etc

UPDATES:
Added script. `python3 analyze.py` produces summaries of assigned and completed numbers to stdout, takes optional filenames for scenario and allocation csv files. 
Note: I'm assuming that these scripts are not intended as anything but developer shim, so I'm not making a whole lot of effort to make them nice

2018-04-20 08:58 UTC, mc-nathan commented
Attempting to test I get:
```
>>> from classes.allocation_analyzer import *
>>> aa = quick_setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "classes/allocation_analyzer.py", line 124, in quick_setup
    aa.read_scenario_from_csv('example.csv')
  File "classes/allocation_analyzer.py", line 62, in read_scenario_from_csv
    self.process_scenario_from_csv(reader)
  File "classes/allocation_analyzer.py", line 72, in process_scenario_from_csv
    judge = Judge(data=row)
  File "classes/judge.py", line 13, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

2018-04-20 09:02 UTC, mc-nathan commented
Got the functional test to work.

2018-04-20 09:28 UTC, mc-nathan requested changes
Overall works as described, but there's some valuable refactoring that should get done that is also pointed to by CodeClimate.

2018-04-20 09:28 UTC, mc-nathan commented on classes/property.py
> +name = Property("name",)
Remove comma or justify with a comment.

2018-04-20 09:28 UTC, mc-nathan commented on classes/judge.py
> +    def is_female(self):
Not a blocker, but we should move away from special casing "female".

2018-04-20 09:28 UTC, mc-nathan commented on classes/entity.py
> +        return self.properties.get(key, "BLANK")
This feels like an odd default.  At minimum I would make it a constant and if it has to be not be None, then I would make it a little more distinct.  Maybe "<BLANK>".  "<NULL>" would be more natural to me than "<BLANK>", but that's a matter of personal preference.

2018-04-20 09:28 UTC, mc-nathan commented on classes/allocation_analyzer.py
> +def quick_setup():
Not a blocker, but I'd rather there was a separate script so we could do something like:
```
python3 analyze.py example.csv tmp.out
```

2018-04-20 09:28 UTC, mc-nathan commented on classes/allocation_analyzer.py
> +def female_judge(assignment, read_counts):
Again, I'd rather this wasn't special cased.

2018-04-20 09:28 UTC, mc-nathan commented on classes/allocation_analyzer.py
> +            summary['min %s' % metric] = -val
I'd like to see counts especially for the min values so we know how much we are missing by.

2018-04-20 09:28 UTC, mc-nathan commented on classes/allocation_analyzer.py
> +def industry_match(assignment, read_counts):
The parallels with program_match strongly suggests that this should be refactored.  Ideally, there should be no feature specific code, but it should all be inferred from the features and values that get used in the input files.

2018-04-20 09:33 UTC, mc-nathan commented
I generally agree with the suggested improvements.  Personally I would not prioritize getting away from the CSV usage, but that's because I find simple shell commands easier to deal with than figuring out everything in the python shell.  Otherwise I would handle them in the order described.

I would also add some count information at least to the mins and there would be no harm in adding them to the maxs.  I think that would allow us to actually understand if we are meeting the criteria or by how much we are missing them.

2018-04-20 20:19 UTC, jonkiparsky commented
@mc-nathan I've rejiggered to have each metric report on how many applications missed the specified target, and removed the mins since they seemed like a poor way to get at this information

2018-04-20 20:19 UTC, jonkiparsky commented on classes/judge.py
> +    def is_female(self):
done

2018-04-20 20:21 UTC, jonkiparsky commented on classes/allocation_analyzer.py
> +            summary['min %s' % metric] = -val
See below, replaced min counts with "missed"

2018-04-22 02:51 UTC, mc-nathan commented
```
$ make code-check
analyze.py:19:1: E303 too many blank lines (3)
analyze.py:28:1: W391 blank line at end of file
classes/allocation_analyzer.py:17:1: E302 expected 2 blank lines, found 1
classes/allocation_analyzer.py:25:61: E231 missing whitespace after ','
classes/allocation_analyzer.py:48:45: W291 trailing whitespace
classes/allocation_analyzer.py:79:29: E221 multiple spaces before operator
classes/allocation_analyzer.py:80:80: E501 line too long (85 > 79 characters)
classes/gender_distribution_metric.py:3:1: E302 expected 2 blank lines, found 1
classes/gender_distribution_metric.py:13:1: W293 blank line contains whitespace
classes/gender_distribution_metric.py:13:1: W391 blank line at end of file
classes/industry_match_metric.py:3:1: E302 expected 2 blank lines, found 1
classes/industry_match_metric.py:8:35: W291 trailing whitespace
classes/judge_role_distribution_metric.py:3:1: E302 expected 2 blank lines, found 1
classes/judge_role_distribution_metric.py:6:1: E302 expected 2 blank lines, found 1
classes/judge_role_distribution_metric.py:14:1: W293 blank line contains whitespace
classes/judge_role_distribution_metric.py:17:1: W293 blank line contains whitespace
classes/judge_role_distribution_metric.py:17:1: W391 blank line at end of file
classes/metric.py:9:5: E303 too many blank lines (2)
classes/metric.py:11:1: W293 blank line contains whitespace
classes/metric.py:27:1: W293 blank line contains whitespace
classes/metric.py:29:80: E501 line too long (81 > 79 characters)
classes/metric.py:35:1: W293 blank line contains whitespace
classes/metric.py:35:1: W391 blank line at end of file
classes/program_match_metric.py:3:1: E302 expected 2 blank lines, found 1
classes/program_match_metric.py:4:19: E211 whitespace before '('
classes/program_match_metric.py:6:1: W293 blank line contains whitespace
classes/total_reads_metric.py:3:1: E302 expected 2 blank lines, found 1
classes/total_reads_metric.py:6:1: W391 blank line at end of file
make: *** [code-check] Error 1
```

2018-04-22 03:06 UTC, mc-nathan approved these changes

2018-04-22 03:06 UTC, merged